global:
  imagePullSecrets:

monitor:
  enabled: true
  port: 8081

diagnosticMode:
  enabled: false

job:
  enabled: false
  restartPolicy: Never
  # workingDir: /app/migrate
  # command: ["dotnet","Ins.Migrator.dll"]
  diagnosticMode:
    enabled: false
  startupProbe:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: False

image:
  repository: nginxinc/nginx-unprivileged
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

containerPorts:
  http: 3000

podAnnotations:

autoscaling:
  enabled: false

secrets:
  enabled: false
  # rolename: cks-role
  # sa: cks-deployer
  # path:
  # - name: "CksAuth__Jwt__Key"
  #   path:
  #     _default: "cks/data/creds"
  #   key: "CksAuth__Jwt__Key"
  # - name: "Estore__Clients__app-cks-bim"
  #   path:
  #     dev: "cks/data/estore/cks-bim"
  #     uat: "cks/data/estore/cks-bim-uat"
  #   key: "Estore__Clients__app-cks-bim"
  # - name: "Estore__Clients__app-cks-documents"
  #   path:
  #     dev: "cks/data/estore/cks-documents"
  #     uat: "cks/data/estore/cks-documents-uat"
  #   key: "Estore__Clients__app-cks-documents"
  # - name: "ConnectionStrings__Default"
  #   path:
  #     dev: "cks/data/database/d-infra-postgres-01.ct.ahml1.ru/cks_dev_4d"
  #     uat: "cks/data/database/u-pgsql-haproxy-02.ct.ahml1.ru/cks_4d"
  #   key: "ConnectionStrings__Default"


replicaCount:
  _default: 1

volumes:
  enabled: false
  path: /app

affinity:
  enabled: true
podAntiAffinityPreset: hard
nodeAffinity:
  enabled: false

hostNetwork: false

podSecurityContext:
  enabled: true
  fsGroup: 101
  runAsUser: 101
  runAsGroup: 101
  # privileged: false

containerSecurityContext:
  enabled: true
  capabilities:
    drop: ["ALL"]
    add: ["SYS_NICE", "NET_BIND_SERVICE"]
    # add: ["CAP_CHOWN", "CAP_NET_BIND_SERVICE", "CAP_SETGID", "CAP_SETUID"]
  allowPrivilegeEscalation: false
  privileged: false

service:
  type: ClusterIP
  ports:
    http: 8080
  nodePorts:
    http: {}

ingress:
  nginx:
    enabled: false
  traefik:
    enabled: false
  enabled: false
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/proxy-body-size: "200m"
  #   nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  #   nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  # hosts:
  #   - host:
  #       _default: dev.example.com
  #       dev: dev.example.com
  #       test: test.example.com
  #     paths:
  #       - path: "/"
  #         pathType: Prefix
  #   - host:
  #       _default: dev.example.com
  #       dev: dev.example.com
  #       test: test.example.com
  #     paths:
  #       - path: "/api/"
  #         pathType: Prefix

serviceAccount:
  create: false

persistence:
  enabled: false

application:
  env:
    # foo:
    #   _default: "bar"
    #   dev: "barr"
    #   test: DOM
